/*
 * Host interop test for the bootloader protocol.
 *
 * Compiles the same bl_crc32.c / bl_proto.c used in the firmware with the host
 * compiler and checks:
 *   1. CRC-32 matches the canonical check value (so it matches Python zlib).
 *   2. Frames generated by gen_frames.py (identical to host/uploader.py) parse.
 *   3. A corrupted frame is rejected via CRC.
 *
 * Usage: test_proto frames.bin   (frames.bin produced by gen_frames.py)
 */
#include <stdio.h>
#include <assert.h>
#include "bl_proto.h"
#include "bl_crc32.h"
#include "bl_flash.h"

int main(int argc, char **argv)
{
	assert(argc == 2);
	assert(bl_crc32((const uint8_t *)"123456789", 9) == 0xCBF43926u);
	printf("crc32 canonical check 0xCBF43926 OK -> zlib/host compatible\n");

	/* flash-region bounds (overflow-safe) */
	assert(bl_offset_in_range(0, 100));
	assert(bl_offset_in_range(BL_APP_SIZE - 4, 4));
	assert(!bl_offset_in_range(BL_APP_SIZE, 4));       /* at the very end */
	assert(!bl_offset_in_range(BL_APP_SIZE - 2, 4));   /* straddles the end */
	assert(!bl_offset_in_range(0xFFFFFFF0u, 0x20));    /* unsigned overflow */
	printf("flash bounds checks OK\n");

	FILE *fp = fopen(argv[1], "rb");
	assert(fp);

	uint8_t buf[8 + BL_MAX_PAYLOAD];
	uint32_t flen;
	int idx = 0;

	while (fread(&flen, 4, 1, fp) == 1) {
		assert(flen <= sizeof buf && fread(buf, 1, flen, fp) == flen);
		struct bl_frame f;
		int r = bl_frame_parse(buf, flen, &f);
		if (idx == 3) {
			assert(r == BL_ERR_CRC);
			printf("frame %d corrupted -> rejected (BL_ERR_CRC) OK\n", idx);
		} else {
			assert(r == BL_OK);
			printf("frame %d parsed: cmd=0x%02X len=%u OK\n", idx, f.cmd, f.len);
		}
		idx++;
	}
	fclose(fp);
	printf("ALL HOST<->TARGET INTEROP ASSERTIONS PASSED\n");
	return 0;
}
